# evaluation_metric: distribution_functions

ai_md_traj:
  path: /workspace/dataset_AIMD/HfO/{STRUCTURE}/OUTCAR
  format: vasp-out
  index: 1000:1999:20  # optional
  n_extend: 2
  out_identifier: 3ps_to_6ps_every_0.06ps
mlff_md_traj:
  Allegro:
    path:  /workspace/for_benchmark/HfO_v1/mlff_trajectories/Allegro/Rmax6_MaxNeigh50_LinearLR_LR5e-3_EP200_E1_EnergyPerAtomMSE_F1_ForcePerDimMSE_EMA99_BS16_1V100-20230408_072648/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  BPNN:
    path:  /workspace/for_benchmark/HfO_v1/mlff_trajectories/BPNN/Rmax6_MaxNeigh50_NormPerAtomOn_LinearLR_LR5e-3_EP200_SAITLoss_BS16_1V100-20230502_075925/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  DimeNet++:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/DimeNet++/Paper_Model_Rmax6_MaxNeigh50_otf_NormPerAtomOn_LinearLR_LR5e-3_EP200_SAITLoss_EMA999_BS8_1V100-20230426_071513/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  GemNet-T:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/GemNet-T/Paper_Model_Rmax6_MaxNeigh50_otf_NormPerAtomOn_LinearLR_LR5e-4_EP200_SAITLoss_EMA999_BS8_1V100-20230426_071146/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  GemNet-dT:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/GemNet-dT/Paper_Model_Rmax6_MaxNeigh50_otf_NormPerAtomOn_LinearLR_LR5e-3_EP200_SAITLoss_EMA999_BS8_1V100-20230426_071855/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  MACE:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/MACE/Rmax6_MaxNeigh50_LinearLR_LR1e-2_EP200_AMSGradOff_E1_EnergyPerAtomMSE_F1_ForcePerDimMSE_EMA99_BS16_1V100-20230424_235240/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  NequIP:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/NequIP/Rmax6_MaxNeigh50_LinearLR_LR5e-3_EP200_E1_EnergyPerAtomMSE_F1_ForcePerDimMSE_EMA99_BS16_1V100-20230407_065101/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  SchNet:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/SchNet/Rmax6_MaxNeigh50_otf_NormPerAtomOn_LinearLR_LR1e-4_EP200_SAITLoss_BS16_1V100-20230428_040751/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
  GemNet-T:  
    path: /workspace/for_benchmark/HfO_v1/mlff_trajectories/GemNet-T/Paper_Model_Rmax6_MaxNeigh50_otf_NormOff_LinearLR_LR5e-4_EP200_SAITLoss_EMA999_BS8_1V100-20230426_070942/{STRUCTURE}/run_20230502_n_super_[2, 2, 2]_20230502/atoms.traj
    format: traj
    index: 50:100   # optional, if not provided, consider all ranges (":")
    n_extend: 1
    out_identifier: 3ps_to_6ps_every_0.06ps
res_out_dir: /workspace/for_benchmark/HfO_v1/materials_metrics/dfs/{STRUCTURE}/n_super_2/norm_off

r_max_rdf: 6.0
dr_rdf: 0.05
r_max_adf: 5.0