# evaluation_metric: eos
eos_type: birchmurnaghan

# model_dir: /workspace/ocp/models/GemNet-dT_HfOv1-dataset2
ref_structure:
  path: /workspace/structures/HfO/1/POSCAR_no_scale
  format: vasp
scale_factors: 
  start: 0.97
  end: 1.05
  interval: 0.005
reference_result:
  dir: /workspace/structures/HfO/1
  volume_energy_fname: energy_volume.dat
  save_eos_fit: True

fit_res_name: compare_eos_gemnet_dT_birchmurnaghan.png
res_out_dir: /workspace/ocp/traj_and_metrics/GemNet-dT_HfOv1-dataset2/1
# fig_out_dir: /workspace/figures/HfO/EoS_eval/1
