includes:
#- NeurIPS23_DnB/configs/SiN_v2.0/base.yml # it can be used after saving scale and pca
- NeurIPS23_DnB/configs/SiN_v2.0/base_rmax6_maxneighbor50.yml # for calculating scale and pca

trainer: forces

model:
  name: bpnn
  # neural network
  nHidden: 240
  nLayer: 5
  trainable: False

  # descriptor : Descriptor parmeter file paths. If you use defeault parameters, comment out.
  #g2_params: None 
  #g4_params: None

  # force
  regress_forces: True

  # graph
  cutoff: 6.0
  max_neighbors: 50
  otf_graph: False
  use_pbc: True

  # data-related arg
  atom_species:
    - N
    - Si

optim:
  batch_size: 16
  eval_batch_size: 16
  num_workers: 2
  max_epochs: 200

  optimizer: Adam
  weight_decay: 1.e-6
  scheduler: LinearLR # SIMPLENN: constant LR
  lr_initial: 5.e-3

  # loss
  energy_coefficient: 1
  loss_energy: energy_per_atom_mse
  force_coefficient: 0.1
  loss_force: force_per_dim_mse

  # SAIT loss
  #energy_coefficient: 1
  #loss_energy: energy_per_atom_mse
  #force_coefficient: 1
  #loss_force: force_per_dim_mse

