includes:
  - NeurIPS23_DnB/configs/SiN_v2.0/base.yml

model:
  name: scn
  # neural network
  num_interactions: 12 # OC20-2M config
  hidden_channels: 1024 # OC20-2M config
  sphere_channels: 128 # OC20-2M config
  sphere_channels_reduce: 128 # OC20-2M config
  num_sphere_samples: 128 # OC20-2M config
  num_basis_functions: 128 # OC20-2M config
  distance_function: "gaussian" # OC20-2M config
  lmax: 6 # OC20-2M config
  mmax: 1 # OC20-2M config
  use_grid: True # OC20-2M config
  num_bands: 2 # OC20-2M config
  num_taps: -1 # OC20-2M config
  basis_width_scalar: 2.0 # OC20-2M config

  # force
  regress_forces: True

  # graph
  cutoff: 6.0 # 8.0 # OC20-2M config
  max_num_neighbors: 50 # 40 # OC20-2M config
  otf_graph: True 
  use_pbc: True # OC20-2M config

optim:
  batch_size: 1 
  eval_batch_size: 1
  num_workers: 2
  max_epochs: 200 # 80 # OC20-2M config
  optimizer: AdamW # OC20-2M config
  optimizer_params: {"amsgrad": True} # OC20-2M config
  clip_grad_norm: 100 # OC20-2M config
  ema_decay: 0.999 # OC20-2M config

  # scheduler
  #scheduler: LambdaLR
  #lr_lambda: step
  #lr_initial: 0.0004 # OC20-2M config
  #lr_gamma: 0.3 # OC20-2M config
  #lr_milestone_epochs: # can be changed 
  #  - 25 # OC20-2M config: 5 / 12
  #  - 40 # OC20-2M config: 7 / 12
  #  - 55 # OC20-2M config: 9 / 12
  #  - 70 # OC20-2M config: 11 / 12
  #warmup_steps: 300 # OC20-2M config: 100
  #warmup_factor: 0.2 # OC20-2M config
  scheduler: LinearLR
  lr_initial: 4.e-4

  # loss
  energy_coefficient: 2 # OC20-2M config
  loss_energy: mae # OC20-2M config
  force_coefficient: 100 # OC20-2M config
  loss_force: l2mae # OC20-2M config
