identifier: run_20230502
seed: 20230502
# device: cuda:6

initial_structure: 
  path: /workspace/dataset_AIMD/HfO/{STRUCTURE}/POSCAR
  format: vasp   # ref: https://wiki.fysik.dtu.dk/ase/ase/io/io.html#ase.io.read
# For now, pbc information for a simulation is found from "initial_structure";
# if not given in "initial_structure", it regarded as pbc=false

out_dir: /workspace/for_benchmark/HfO_v1/mlff_trajectories/{MODEL}/{STRUCTURE}

timestep_fs: 3
simulation_time_ps: 9
temperature_K: {TEMP_K}
thermostat: NoseHoover   # thermostat: Langevin
nh_relax_timesteps: 20   # langevin_thermostat_coeff: 0.001
save_freq: 20

n_super: [ 2, 2, 2]  # optional