includes:
- NeurIPS23_DnB/configs/SiN_v1.0/base.yml

trainer: forces

model:
  name: gemnet_t
  # neural network
  num_spherical: 7 # OC20 GemNet-dT config
  num_radial: 6 # github config
  num_blocks: 4 # github config
  emb_size_atom: 128 # github config
  emb_size_edge: 128 # github config
  emb_size_trip: 64 # github config
  emb_size_rbf: 16 # github config
  emb_size_cbf: 16 # github config
  emb_size_bil_trip: 64 # github config
  num_before_skip: 1 # github config
  num_after_skip: 1 # github config
  num_concat: 1 # github config
  num_atom: 2 # github config
  rbf:
    name: spherical_bessel # paper config
  envelope:
    name: polynomial # OC20 GemNet-dT config
    exponent: 5 # OC20 GemNet-dT config
  cbf:
    name: spherical_harmonics # OC20 GemNet-dT config
  extensive: True # OC20 GemNet-dT config
  output_init: HeOrthogonal # OC20 GemNet-dT config
  activation: silu # OC20 GemNet-dT config

  # data-related arg
  scale_file: NeurIPS23_DnB/configs/SiN_v1.0/auxiliary/gemnet-T_paper_model_scale.json

  # force
  regress_forces: True
  direct_forces: False

  # graph
  cutoff: 6.0 # OC20 GemNet-dT config
  max_neighbors: 50 # OC20 GemNet-dT config
  otf_graph: True
  use_pbc: True # periodic system

optim:
  batch_size: 4 # 32: OC20 GemNet-dT config
  eval_batch_size: 4 # 32: OC20 GemNet-dT config
  num_workers: 2 # OC20 GemNet-dT config
  optimizer: AdamW # OC20 GemNet-dT config
  optimizer_params: {"amsgrad": True} # OC20 GemNet-dT config
  max_epochs: 200 # 80: OC20 GemNet-dT config
  ema_decay: 0.999 # OC20 GemNet-dT config
  clip_grad_norm: 10 # OC20 GemNet-dT config

  # scheduler
  # ReduceLROnPlateau : OC20 GemNet-dT config
  #scheduler: ReduceLROnPlateau # OC20 GemNet-dT config
  #lr_initial: 5.e-4 # OC20 GemNet-dT config
  #mode: min # OC20 GemNet-dT config
  #factor: 0.8 # OC20 GemNet-dT config
  #patience: 3 # OC20 GemNet-dT config

  scheduler: LinearLR
  lr_initial: 5.e-4 

  # loss
  energy_coefficient: 1 # OC20 GemNet-dT config
  loss_energy: mae # OC20 GemNet-dT config
  force_coefficient: 100 # OC20 GemNet-dT config
  loss_force: l2mae # OC20 GemNet-dT config
