includes:
- NeurIPS23_DnB/configs/SiN_v1.0/base_rmax5.yml

model:
  name: gemnet_t
  num_spherical: 7
  num_radial: 16
  num_blocks: 3
  emb_size_atom: 64
  emb_size_edge: 64
  emb_size_trip: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  cutoff: 5.0
  max_neighbors: 50 ## 10000
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  extensive: True
  otf_graph: False ## True = on-the-fly (otf) computing graph
  output_init: HeOrthogonal
  activation: silu
  scale_file: NeurIPS23_DnB/configs/SiN_v1.0/auxiliary/scale_file_gemnet-T_ocp_mini.json
  regress_forces: True
  direct_forces: False #True
  use_pbc: True

optim:
  batch_size: 8
  eval_batch_size: 8
  #eval_every: 534 ## 1 epoch
  num_workers: 2
  lr_initial: 0.005 #5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  #scheduler: ReduceLROnPlateau
  #mode: min
  #factor: 0.8
  #patience: 3
  scheduler: LinearLR
  start_factor: 1.0
  end_factor: 0.0
  max_epochs: 300
  ema_decay: 0.999
  clip_grad_norm: 10
  energy_coefficient: 1
  loss_energy: energy_per_atom_mse
  force_coefficient: 1 ## 100
  loss_force: force_per_dim_mse #l2mae
