includes:
- configs/train/HfO/base_rmax6_maxneighbor50.yml # for calculating scale and pca

trainer: forces

model:
  name: bpnn
  # neural network
  nHidden: 240
  nLayer: 5
  trainable: False

  # descriptor : Descriptor parmeter file paths. If you use defeault parameters, comment out.
  #g2_params: None 
  #g4_params: None

  # force
  regress_forces: True

  # graph
  cutoff: 6.0
  max_neighbors: 50
  otf_graph: False
  use_pbc: True

  # data-related arg
  atom_species:
    - O
    - Hf

optim:
  batch_size: 16
  eval_batch_size: 16
  num_workers: 2
  max_epochs: 200

  optimizer: Adam
  weight_decay: 1.e-6
  scheduler: LinearLR
  lr_initial: 5.e-3

  energy_coefficient: 1
  force_coefficient: 1

  # MSE-based loss
  loss_energy: energy_per_atom_mse
  loss_force: force_per_dim_mse

  # MAE-based loss
  #loss_energy: energy_per_atom_mae
  #loss_force: l2mae
