identifier: md_sim

seed: 2023

initial_structure: 
  path: datasets/{DATA}_eval/dfs/{STRUCTURE}/POSCAR
  format: vasp   # ref: https://wiki.fysik.dtu.dk/ase/ase/io/io.html#ase.io.read
# For now, pbc information for a simulation is found from "initial_structure";
# if not given in "initial_structure", it regarded as pbc=false

out_dir: eval_results/{DATA}/mlff_trajectories/{MODEL}/{STRUCTURE}

timestep_fs: 3
simulation_time_ps: 9
temperature_K: {TEMP_K}
thermostat: NoseHoover   # thermostat: Langevin
nh_relax_timesteps: 20   # langevin_thermostat_coeff: 0.001
save_freq: 20

