includes:
- NeurIPS23_DnB/configs/OC20-2M/base.yml

model:
  name: dimenetplusplus
  hidden_channels: 192
  out_emb_channels: 192
  num_blocks: 3
  cutoff: 6.0
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 32.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  ## GBS = 384 (32 GPUs)
  ## 2M samples, 1 epoch = 5208.333333 steps
  batch_size: 12
  eval_batch_size: 12
  eval_every: 10000
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 20833  ## 4 epochs
    - 31250  ## 6 epochs
    - 41666  ## 8 epochs
  warmup_steps: 10416 ## 2 epochs
  warmup_factor: 0.2
  max_epochs: 15
  force_coefficient: 50
