includes:
- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base_rmax5.yml

trainer: forces_nequip

model:
  name: allegro
  # neural network
  model_builders: # Allegro default config
    - Allegro
    - PerSpeciesRescale
    - ForceOutput
    - RescaleEnergyEtc
  num_layers: 3 # rmd17 config (paper)
  l_max: 3
  parity: o3_full # rmd17 config (paper)
  num_basis: 8 # rmd17 config (paper)
  BesselBasis_trainable: True # rmd17 config (paper)
  PolynomialCutoff_p: 6 # rmd17 config (paper)
  env_embed_multiplicity: 128 # rmd17 config (paper)
  two_body_latent_mlp_latent_dimensions: [128, 256, 512, 1024] # rmd17 config (paper)
  latent_mlp_latent_dimensions: [1024, 1024, 1024] # rmd17 config (paper)
  edge_eng_mlp_latent_dimensions: [128] # rmd17 config (paper)

  # data-related arg
  chemical_symbols:
    - H
    - C
    - O

  # force
  regress_forces: True

  # graph
  cutoff: 7.0 # rmd17 config (9.0 only for Naphtalene)
  otf_graph: False 
  use_pbc: False # non-periodic system

optim:
  batch_size: 5 # rmd17 config (paper)
  eval_batch_size: 50 # rmd17 config (paper)
  num_workers: 2
  max_epochs: 2000 # GemNet budget
  ema_decay: 0.99 # rmd17 config (paper)

  optimizer: Adam # rmd17 config (paper)
  optimizer_params: {"amsgrad": False} # rmd17 config (paper)
  scheduler: ReduceLROnPlateau # rmd17 config (paper)
  lr_initial: 0.002 # rmd17 config (paper)
  patience: 100 # rmd17 config (paper)
  factor: 0.8 # rmd17 config (paper)

  # loss function is defined in Eq. (34) in Allegro arXiv paper
  energy_coefficient: 1 # rmd17 config (paper)
  loss_energy: mse # rmd17 config (paper)
  force_coefficient: 1000 # rmd17 config (paper)
  loss_force: force_per_dim_mse # rmd17 config (paper)

