dataset:
  aspirin:
  - src: /home/workspace/MLFF/rMD17/aspirin/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/aspirin/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/aspirin/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  azobenzene:
  - src: /home/workspace/MLFF/rMD17/azobenzene/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/azobenzene/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/azobenzene/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  benzene:
  - src: /home/workspace/MLFF/rMD17/benzene/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/benzene/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/benzene/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  ethanol:
  - src: /home/workspace/MLFF/rMD17/ethanol/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/ethanol/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/ethanol/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  malonaldehyde:
  - src: /home/workspace/MLFF/rMD17/malonaldehyde/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/malonaldehyde/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/malonaldehyde/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  naphthalene:
  - src: /home/workspace/MLFF/rMD17/naphthalene/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/naphthalene/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/naphthalene/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  paracetamol:
  - src: /home/workspace/MLFF/rMD17/paracetamol/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/paracetamol/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/paracetamol/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  salicylic:
  - src: /home/workspace/MLFF/rMD17/salicylic/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/salicylic/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/salicylic/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  toluene:
  - src: /home/workspace/MLFF/rMD17/toluene/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/toluene/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/toluene/atom_graph_rmax4.0_sampling_step_100/test.lmdb 
  uracil:
  - src: /home/workspace/MLFF/rMD17/uracil/atom_graph_rmax4.0_sampling_step_100/train.lmdb 
    normalize_labels: True
  - src: /home/workspace/MLFF/rMD17/uracil/atom_graph_rmax4.0_sampling_step_100/valid.lmdb 
  - src: /home/workspace/MLFF/rMD17/uracil/atom_graph_rmax4.0_sampling_step_100/test.lmdb 

logger: files #tensorboard

task:
  dataset: lmdb
  description: "Regressing to energies and forces for DFT trajectories (rMD17) with no fixed atoms"
  metrics: 
    - energy_per_atom_mae
    - forces_mae
    - forces_mse
  primary_metric: forces_mae
  train_on_free_atoms: False
  eval_on_free_atoms: False
