includes:
- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base.yml # atom cloud (without edges)
#- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base_rmax5.yml # atom graph (with rmax 5.0)

trainer: forces

model:
  name: gemnet_t
  # neural network
  num_spherical: 7 # paper 
  num_radial: 6 # paper
  num_blocks: 4 # paper
  emb_size_atom: 128 # paper
  emb_size_edge: 128 # paper
  emb_size_trip: 64 # paper
  emb_size_rbf: 16 # paper
  emb_size_cbf: 16 # paper
  emb_size_bil_trip: 64 # paper
  num_before_skip: 1 # paper
  num_after_skip: 1 # paper
  num_concat: 1 # paper
  num_atom: 2 # paper
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  extensive: True
  output_init: HeOrthogonal
  activation: silu

  # data-related arg
  scale_file: /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/auxiliary/gemnet-dT_sampling_step_100/scale_file_compound.json

  # force
  regress_forces: True
  direct_forces: True

  # graph
  cutoff: 5.0 # paper
  max_neighbors: 50
  otf_graph: True # True when atom cloud is used
  use_pbc: False # non-periodic system

optim:
  batch_size: 1 # paper
  eval_batch_size: 50
  num_workers: 2
  optimizer: AdamW # paper
  optimizer_params: {"amsgrad": True, "weight_decay": 2.e-6}
  max_epochs: 2000 
  ema_decay: 0.999 # paper
  clip_grad_norm: 10 # paper
  # no warmup ... paper : warmup epoch 10

  # scheduler
  scheduler: ReduceLROnPlateau
  lr_initial: 1.e-3 # paper
  mode: min
  factor: 0.5 # paper
  patience: 50 # paper
  cooldown: 50 # paper

  # loss function is defined in Eq. (35) in GemNet paper suppl. (NeurIPS21)
  energy_coefficient: 0.001
  loss_energy: mae
  force_coefficient: 0.999
  loss_force: l2mae
