includes:
- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base_rmax5.yml

trainer: forces_nequip

model:
  name: nequip
  # neural network
  model_builders: # NequIP default config
    - SimpleIrrepsConfig
    - EnergyModel
    - PerSpeciesRescale
    - ForceOutput
    - RescaleEnergyEtc
  num_layers: 5 # rmd17 config
  l_max: 3
  parity: True # rmd17 config
  num_features: 64 # rmd17 config
  num_basis: 8 # rmd17 config
  BesselBasis_trainable: True # rmd17 config
  PolynomialCutoff_p: 6 # rmd17 config
  invariant_layers: 3 # rmd17 config
  invariant_neurons: 64 # rmd17 config
  avg_num_neighbors: 10.0 # rmd17 config
  use_sc: True # rmd17 config
  nonlinearity_type: gate # rmd17 config
  resnet: False # rmd17 config
  nonlinearity_scalars: # rmd17 config
    e: silu
    o: tanh
  nonlinearity_gates: # rmd17 config
    e: silu
    o: tanh

  # data-related arg
  chemical_symbols:
    - H
    - C
    - O

  # force
  regress_forces: True

  # graph
  cutoff: 5.0 #  rmd17 config
  otf_graph: False 
  use_pbc: False # non-periodic system

optim:
  batch_size: 5 # rmd17 config
  eval_batch_size: 50
  num_workers: 2
  max_epochs: 2000 # GemNet budget
  ema_decay: 0.99 # rmd17 config

  optimizer: Adam # rmd17 config
  optimizer_params: {"amsgrad": True} # rmd17 config
  scheduler: ReduceLROnPlateau # rmd17 config
  lr_initial: 0.01 # rmd17 config
  patience: 50 # rmd17 config
  factor: 0.8 # rmd17 config

  # loss function is defined in Eq. (9) in NequIP arXiv paper
  energy_coefficient: 1 # rmd17 config
  loss_energy: mse # rmd17 config
  force_coefficient: 1000 # rmd17 config
  loss_force: force_per_dim_mse # rmd17 config

