includes:
- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base_rmax5.yml

trainer: forces_nequip

model:
  name: nequip
  cutoff: 5.0 # default: 4.0 in paper
  regress_forces: True
  use_pbc: False
  otf_graph: False

  # neural network
  model_builders:
    - SimpleIrrepsConfig
    - EnergyModel
    - PerSpeciesRescale
    - ForceOutput
    - RescaleEnergyEtc
  num_layers: 5
  l_max: 3
  parity: True
  num_features: 32
  num_basis: 8
  BesselBasis_trainable: True
  PolynomialCutoff_p: 6
  invariant_layers: 2
  invariant_neurons: 64
  avg_num_neighbors: auto
  use_sc: True
  nonlinearity_type: gate
  resnet: False
  nonlinearity_scalars:
    e: silu
    o: tanh
  nonlinearity_gates:
    e: silu
    o: tanh

  # data-related arg
  chemical_symbols:
    - H
    - C
    - O

optim:
  batch_size: 5 
  eval_batch_size: 16
  num_workers: 2
  max_epochs: 2000
  ema_decay: 0.99

  optimizer: Adam
  optimizer_params: {"amsgrad": False}
  scheduler: ReduceLROnPlateau
  lr_initial: 0.01
  patience: 50
  factor: 0.8

  energy_coefficient: 1
  loss_energy: mse_per_atom
  force_coefficient: 1000
  loss_force: mse_per_dim

