includes:
- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base.yml # atom cloud (without edges)
#- /nas/SAIT-MLFF-Framework/NeurIPS23_DnB/configs/rMD17/base_rmax5.yml # atom graph (with rmax 5.0)

trainer: forces

model:
  name: scn
  # neural network
  num_interactions: 12 # SCN OC20-2M config
  hidden_channels: 256 # denoted by H : 1024 in OC20-2M, reduce by 1/4 for rMD17, as in GemNet
  sphere_channels: 64 # denoted by C : 128 in OC20-2M
  sphere_channels_reduce: 64 # denoted by C : 128 in OC20-2M
  num_sphere_samples: 64 # denoted by E : 128 in OC20-2M
  num_basis_functions: 64 # 128 in OC20-2M
  distance_function: "gaussian" # SCN OC20-2M config
  lmax: 6 # SCN OC20-2M config 
  mmax: 1 # SCN OC20-2M config
  use_grid: True # SCN OC20-2M config
  num_bands: 1 # SCN OC20-2M config
  num_taps: 1 # SCN OC20-2M config
  basis_width_scalar: 2.0 # SCN OC20-2M config

  # force
  # note that SCN is a direct force prediction model
  regress_forces: True
  direct_forces: True # SCN paper

  # graph
  cutoff: 5.0 # PaiNN
  max_num_neighbors: 40 # SCN OC20-2M config
  otf_graph: True # True when atom cloud is used
  use_pbc: False # non-periodic system

optim:
  batch_size: 10 # PaiNN paper
  eval_batch_size: 50 
  num_workers: 2
  optimizer: Adam # PaiNN paper
  max_epochs: 2000 # GemNet paper
  ema_decay: 0.99 # SchNet paper (followed by PaiNN)
  clip_grad_norm: 100 # SCN OC20-2M config

  # scheduler (PaiNN)
  # but for small molecule data, it may follow PaiNN
  scheduler: ReduceLROnPlateau # PaiNN paper
  lr_initial: 1.e-3 # PaiNN paper
  factor: 0.5 # PaiNN paper
  patience: 50 # PaiNN paper

  # loss function described in Section 3.1 in SCN paper (NeurIPS22)
  # but for small molecule data, it may follow PaiNN
  energy_coefficient: 0.01 # PaiNN paper
  loss_energy: mse # PaiNN paper
  force_coefficient: 0.99 # PaiNN paper
  loss_force: force_per_dim_mse # PaiNN paper
