dataset:
  # atom cloud
  - src: /home/workspace/MLFF/dataset/SiN/atom_cloud/train.lmdb
    normalize_labels: True
    per_atom: True
    normalize_labels_json: /home/workspace/MLFF/dataset/SiN/atom_cloud/normalize_stats.json
  - src: /home/workspace/MLFF/dataset/SiN/atom_cloud/valid_shuffled.lmdb
  - src: /home/workspace/MLFF/dataset/SiN/atom_cloud/test_shuffled.lmdb

logger: files

task:
  dataset: lmdb
  description: "Regressing to energies and forces for DFT trajectories of SiN"
  metrics: 
    - energy_per_atom_mae
    - energy_per_atom_mse
    - forces_mae
    - forces_mse
  primary_metric: forces_mse
  train_on_free_atoms: False
  eval_on_free_atoms: False

