includes:
- configs/train/SiN/base.yml

trainer: forces

model:
  name: dimenetplusplus
  # neural network
  hidden_channels: 128 
  out_emb_channels: 256
  int_emb_size: 64 
  basis_emb_size: 8 
  num_blocks: 4 
  num_radial: 6 
  num_spherical: 7 
  num_before_skip: 1  
  num_after_skip: 2 
  num_output_layers: 3 

  # force
  regress_forces: True

  # graph
  cutoff: 6.0 
  # max_neighbors: 50 # this is explictly defined in SchNet class
  otf_graph: True 
  use_pbc: True 

optim:
  batch_size: 3
  eval_batch_size: 3
  num_workers: 2
  max_epochs: 200 

  optimizer: Adam 
  scheduler: LinearLR
  lr_initial: 1.e-4

  energy_coefficient: 1
  force_coefficient: 1

  # MSE-based loss
  loss_energy: energy_per_atom_mse
  loss_force: force_per_dim_mse

  # MAE-based loss
  #loss_energy: energy_per_atom_mae
  #loss_force: l2mae
