includes:
- configs/train/SiN/base_rmax6_maxneighbor50.yml

trainer: forces_nequip

model:
  name: nequip
  # neural network
  model_builders: 
    - SimpleIrrepsConfig
    - EnergyModel
    - PerSpeciesRescale
    - ForceOutput
    - RescaleEnergyEtc
  num_layers: 4 
  l_max: 2
  parity: True
  num_features: 32
  num_basis: 8
  BesselBasis_trainable: True
  PolynomialCutoff_p: 6
  invariant_layers: 2
  invariant_neurons: 64 
  avg_num_neighbors: auto # 'auto' requires to set 'initialize' as True, meaning that data statistics will be calculated if the statistics file does not exist
  use_sc: True
  nonlinearity_type: gate
  resnet: False
  nonlinearity_scalars:
    e: silu
    o: tanh
  nonlinearity_gates:
    e: silu
    o: tanh

  # force
  regress_forces: True

  # graph
  cutoff: 6.0 
  max_neighbors: 50 
  otf_graph: False 
  use_pbc: True 

  # data-related arg
  chemical_symbols:
    - N
    - Si

optim:
  batch_size: 16 
  eval_batch_size: 16
  num_workers: 2
  max_epochs: 200

  optimizer: Adam
  optimizer_params: {"amsgrad": False}
  scheduler: LinearLR
  lr_initial: 0.005
  ema_decay: 0.99

  energy_coefficient: 1
  force_coefficient: 1

  # MSE-based loss
  loss_energy: energy_per_atom_mse
  loss_force: force_per_dim_mse

  # MAE-based loss
  #loss_energy: energy_per_atom_mae
  #loss_force: l2mae
